In [11]:
import numpy as np
import os
import pandas as pd
import tensorflow as tf
import matplotlib
from tensorflow import keras
from tensorflow.keras import layers

In [12]:
data_path = os.chdir("C:\\Users\\NoMad\\PycharmProjects\\SANEM\\movements")

In [13]:
# другой вариант таблицы, где 25 - число движений, 24 - число пространственных переменных, n - число моментов, потребовавшихся для записи движения
# (25, 24, n)
maxlen = 0
flag = False
for i in range(1,7):
    for j in range(1,10):
        data1 = np.array(pd.read_csv(f"m0{i}_s0{j}_e01_positions.txt", sep=','))
        data1 = np.array([data1[:, 42:].transpose()])
        if(maxlen<data1.shape[2]):
            maxlen = data1.shape[2]

for i in range(1,7):
    for j in range(1,5):
        if(flag==False):
            data1 = np.array(pd.read_csv(f"m0{i}_s0{j}_e01_positions.txt", sep=','))
            data1 = np.array([data1[:, 42:].transpose()])
            x_train = np.zeros((data1.shape[0],data1.shape[1],maxlen))
            x_train[:data1.shape[0],:data1.shape[1],:data1.shape[2]] = data1
            flag=True
            continue
        data1 = np.array(pd.read_csv(f"m0{i}_s0{j}_e01_positions.txt", sep=','))
        data1 = np.array([data1[:, 42:].transpose()])
        if(data1.shape[2]<maxlen):
            newdata = np.zeros((data1.shape[0],data1.shape[1],maxlen))
            newdata[:data1.shape[0],:data1.shape[1],:data1.shape[2]] = data1
            x_train = np.append(x_train, newdata, axis=0)
        elif(data1.shape[2]==maxlen):
            x_train = np.append(x_train, data1, axis=0)

print(x_train.shape)

(24, 24, 159)


In [14]:
x_train = x_train.reshape(x_train.shape[0], 24, x_train.shape[2], 1)
x_train = x_train.astype('float32')
print(x_train.shape)

(24, 24, 159, 1)


In [15]:
# проверочные данные:
predict_move_1 = np.array(pd.read_csv('m01_s01_e05_positions.txt', sep=','))
predict_move_1 = np.array([predict_move_1[:x_train.shape[2], 42:].transpose()])
if(predict_move_1.shape[2]<maxlen):
    newdata = np.zeros((predict_move_1.shape[0],predict_move_1.shape[1],maxlen))
    newdata[:predict_move_1.shape[0],:predict_move_1.shape[1],:predict_move_1.shape[2]] = predict_move_1
    predict_move_1 = newdata
print(predict_move_1.shape)
predict_move_1 = predict_move_1.reshape(predict_move_1.shape[0], 24, predict_move_1.shape[2], 1)
predict_move_1 = predict_move_1.astype('float32')
print("predict_move_1 = ",predict_move_1.shape)

predict_move_2 = np.array(pd.read_csv('m02_s01_e01_positions.txt', sep=','))
predict_move_2 = np.array([predict_move_2[:x_train.shape[2], 42:].transpose()])
if(predict_move_2.shape[2]<maxlen):
    newdata = np.zeros((predict_move_2.shape[0],predict_move_2.shape[1],maxlen))
    newdata[:predict_move_2.shape[0],:predict_move_2.shape[1],:predict_move_2.shape[2]] = predict_move_2
    predict_move_2 = newdata
print(predict_move_2.shape)
predict_move_2 = predict_move_2.reshape(predict_move_2.shape[0], 24, predict_move_2.shape[2], 1)
predict_move_2 = predict_move_2.astype('float32')
print("predict_move_2 = ",predict_move_2.shape)

predict_move_3 = np.array(pd.read_csv('m03_s02_e02_positions.txt', sep=','))
predict_move_3 = np.array([predict_move_3[:x_train.shape[2], 42:].transpose()])
if(predict_move_3.shape[2]<maxlen):
    newdata = np.zeros((predict_move_3.shape[0],predict_move_3.shape[1],maxlen))
    newdata[:predict_move_3.shape[0],:predict_move_3.shape[1],:predict_move_3.shape[2]] = predict_move_3
    predict_move_3 = newdata
print(predict_move_3.shape)
predict_move_3 = predict_move_3.reshape(predict_move_3.shape[0], 24, predict_move_3.shape[2], 1)
predict_move_3 = predict_move_3.astype('float32')
print("predict_move_3 = ",predict_move_3.shape)

predict_move_4 = np.array(pd.read_csv('m04_s01_e01_positions.txt', sep=','))
predict_move_4 = np.array([predict_move_4[:x_train.shape[2], 42:].transpose()])
if(predict_move_4.shape[2]<maxlen):
    newdata = np.zeros((predict_move_4.shape[0],predict_move_4.shape[1],maxlen))
    newdata[:predict_move_4.shape[0],:predict_move_4.shape[1],:predict_move_4.shape[2]] = predict_move_4
    predict_move_4 = newdata
print(predict_move_4.shape)
predict_move_4 = predict_move_4.reshape(predict_move_4.shape[0], 24, predict_move_4.shape[2], 1)
predict_move_4 = predict_move_4.astype('float32')
print("predict_move_4 = ",predict_move_4.shape)

predict_move_5 = np.array(pd.read_csv('m05_s01_e01_positions.txt', sep=','))
predict_move_5 = np.array([predict_move_5[:x_train.shape[2], 42:].transpose()])
if(predict_move_5.shape[2]<maxlen):
    newdata = np.zeros((predict_move_5.shape[0],predict_move_5.shape[1],maxlen))
    newdata[:predict_move_5.shape[0],:predict_move_5.shape[1],:predict_move_5.shape[2]] = predict_move_5
    predict_move_5 = newdata
print(predict_move_5.shape)
predict_move_5 = predict_move_5.reshape(predict_move_5.shape[0], 24, predict_move_5.shape[2], 1)
predict_move_5 = predict_move_5.astype('float32')
print("predict_move_5 = ",predict_move_5.shape)

predict_move_6 = np.array(pd.read_csv('m06_s01_e05_positions.txt', sep=','))
predict_move_6 = np.array([predict_move_6[:x_train.shape[2], 42:].transpose()])
if(predict_move_6.shape[2]<maxlen):
    newdata = np.zeros((predict_move_6.shape[0],predict_move_6.shape[1],maxlen))
    newdata[:predict_move_6.shape[0],:predict_move_6.shape[1],:predict_move_6.shape[2]] = predict_move_6
    predict_move_6 = newdata
print(predict_move_6.shape)
predict_move_6 = predict_move_6.reshape(predict_move_6.shape[0], 24, predict_move_6.shape[2], 1)
predict_move_6 = predict_move_6.astype('float32')
print("predict_move_6 = ",predict_move_6.shape)

(1, 24, 159)
predict_move_1 =  (1, 24, 159, 1)
(1, 24, 159)
predict_move_2 =  (1, 24, 159, 1)
(1, 24, 159)
predict_move_3 =  (1, 24, 159, 1)
(1, 24, 159)
predict_move_4 =  (1, 24, 159, 1)
(1, 24, 159)
predict_move_5 =  (1, 24, 159, 1)
(1, 24, 159)
predict_move_6 =  (1, 24, 159, 1)


In [16]:
# выходной набор данных. Столбец с единицей соответствует номеру соответствующего движения (движений всего 6) 
# y_train = [[1,0,0,0,0,0], [1,0,0,0,0,0], [1,0,0,0,0,0], [1,0,0,0,0,0], [1,0,0,0,0,0],
#            [0,1,0,0,0,0], [0,1,0,0,0,0], [0,1,0,0,0,0], [0,1,0,0,0,0],
#            [0,0,1,0,0,0], [0,0,1,0,0,0], [0,0,1,0,0,0], [0,0,1,0,0,0],
#            [0,0,0,1,0,0], [0,0,0,1,0,0], [0,0,0,1,0,0], [0,0,0,1,0,0],
#            [0,0,0,0,1,0], [0,0,0,0,1,0], [0,0,0,0,1,0], [0,0,0,0,1,0],
#            [0,0,0,0,0,1], [0,0,0,0,0,1], [0,0,0,0,0,1]]

y_train = [0,0,0,0,1,1,1,1,2,2,2,2,3,3,3,3,4,4,4,4,5,5,5,5]
y_train = np.array(y_train, dtype=np.float32)
y_train = keras.utils.to_categorical(y_train)
print(y_train)

[[1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]]


In [462]:
# другой вариант нейросети (сверточная)
input = keras.Input(shape=(24,x_train.shape[2],1))
inputs = layers.Convolution2D(24, input_shape=(24,), kernel_size=(3,1), activation="softmax")(input)
hidden1 = layers.Dense(8, activation="softmax")(inputs)
hidden1 = layers.Dropout(0.2)(hidden1)
h1 = layers.Flatten()(hidden1)
outputs = layers.Dense(6, activation="sigmoid")(h1)

seq_model = keras.Model(inputs=input, outputs=outputs, name="sequential_or_what")
seq_model.summary()


Model: "sequential_or_what"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_69 (InputLayer)        [(None, 24, 159, 1)]      0         
_________________________________________________________________
conv2d_68 (Conv2D)           (None, 22, 159, 24)       96        
_________________________________________________________________
dense_134 (Dense)            (None, 22, 159, 8)        200       
_________________________________________________________________
dropout_66 (Dropout)         (None, 22, 159, 8)        0         
_________________________________________________________________
flatten_66 (Flatten)         (None, 27984)             0         
_________________________________________________________________
dense_135 (Dense)            (None, 6)                 167910    
Total params: 168,206
Trainable params: 168,206
Non-trainable params: 0
__________________________________________

In [463]:
seq_model.compile(
    optimizer=keras.optimizers.Nadam(),
    loss=keras.losses.BinaryCrossentropy(),
    metrics=['accuracy']
)

In [471]:
seq_model.fit(x_train,y_train,epochs=200,batch_size=2)

Epoch 1/100
12/12 [==============================] - 0s 12ms/step - loss: 0.1726 - accuracy: 0.8333
Epoch 2/100
12/12 [==============================] - 0s 12ms/step - loss: 0.1819 - accuracy: 0.7917
Epoch 3/100
12/12 [==============================] - 0s 12ms/step - loss: 0.1472 - accuracy: 0.9167
Epoch 4/100
12/12 [==============================] - 0s 11ms/step - loss: 0.1757 - accuracy: 0.8333
Epoch 5/100
12/12 [==============================] - 0s 14ms/step - loss: 0.1989 - accuracy: 0.6667
Epoch 6/100
12/12 [==============================] - 0s 13ms/step - loss: 0.1435 - accuracy: 0.9167
Epoch 7/100
12/12 [==============================] - 0s 14ms/step - loss: 0.1921 - accuracy: 0.7500
Epoch 8/100
12/12 [==============================] - 0s 13ms/step - loss: 0.1683 - accuracy: 0.7500
Epoch 9/100
12/12 [==============================] - 0s 13ms/step - loss: 0.1373 - accuracy: 0.7500
Epoch 10/100
12/12 [==============================] - 0s 13ms/step - loss: 0.1606 - accuracy: 0.7917

12/12 [==============================] - 0s 14ms/step - loss: 0.0358 - accuracy: 0.9583
Epoch 83/100
12/12 [==============================] - 0s 12ms/step - loss: 0.0249 - accuracy: 1.0000
Epoch 84/100
12/12 [==============================] - 0s 12ms/step - loss: 0.0267 - accuracy: 1.0000
Epoch 85/100
12/12 [==============================] - 0s 13ms/step - loss: 0.0220 - accuracy: 1.0000
Epoch 86/100
12/12 [==============================] - 0s 12ms/step - loss: 0.0219 - accuracy: 1.0000
Epoch 87/100
12/12 [==============================] - 0s 12ms/step - loss: 0.0245 - accuracy: 1.0000
Epoch 88/100
12/12 [==============================] - 0s 13ms/step - loss: 0.0146 - accuracy: 1.0000
Epoch 89/100
12/12 [==============================] - 0s 13ms/step - loss: 0.0216 - accuracy: 1.0000
Epoch 90/100
12/12 [==============================] - 0s 13ms/step - loss: 0.0188 - accuracy: 1.0000
Epoch 91/100
12/12 [==============================] - 0s 12ms/step - loss: 0.0287 - accuracy: 0.9583
Epo

In [484]:
model_json = seq_model.to_json()
with open("C:\\Users\\NoMad\\PycharmProjects\\SANEM\\model\\1model.json", "w") as json_file:
    json_file.write(model_json)
seq_model.save_weights("C:\\Users\\NoMad\\PycharmProjects\\SANEM\\model\\1weights.h5")

In [472]:
predictArr = seq_model.predict(predict_move_1)
print(predictArr[0])

maxPercentage = 0
for i in enumerate(predictArr[0]):
    if(i[1]>maxPercentage):
        maxPercentage=i[1]
        move=i[0]+1     
print(round(maxPercentage*100, 2),"% this is move № ", move)

[9.4568950e-01 7.7411195e-04 9.7303919e-02 7.0089670e-03 4.1770683e-05
 5.4358966e-06]
94.57 % this is move №  1


In [473]:
predictArr = seq_model.predict(predict_move_2)
print(predictArr[0])

maxPercentage = 0
for i in enumerate(predictArr[0]):
    if(i[1]>maxPercentage):
        maxPercentage=i[1]
        move=i[0]+1     
print(round(maxPercentage*100, 2),"% this is move № ", move)

[2.7004173e-03 9.7468501e-01 4.4411151e-03 5.6746288e-05 1.6833897e-04
 8.7626457e-02]
97.47 % this is move №  2


In [474]:
predictArr = seq_model.predict(predict_move_3)
print(predictArr[0])

maxPercentage = 0
for i in enumerate(predictArr[0]):
    if(i[1]>maxPercentage):
        maxPercentage=i[1]
        move=i[0]+1     
print(round(maxPercentage*100, 2),"% this is move № ", move)

[2.1359934e-08 4.3531734e-04 3.6409649e-04 1.3643138e-04 9.9838674e-01
 2.0663261e-05]
99.84 % this is move №  5


In [475]:
predictArr = seq_model.predict(predict_move_4)
print(predictArr[0])

maxPercentage = 0
for i in enumerate(predictArr[0]):
    if(i[1]>maxPercentage):
        maxPercentage=i[1]
        move=i[0]+1     
print(round(maxPercentage*100, 2),"% this is move № ", move)

[5.8440124e-03 5.2374537e-05 4.5995776e-02 9.6409690e-01 3.7929078e-03
 2.8358176e-04]
96.41 % this is move №  4


In [476]:
predictArr = seq_model.predict(predict_move_5)
print(predictArr[0])

maxPercentage = 0
for i in enumerate(predictArr[0]):
    if(i[1]>maxPercentage):
        maxPercentage=i[1]
        move=i[0]+1     
print(round(maxPercentage*100, 2),"% this is move № ", move)

[1.3401434e-02 7.0877986e-06 1.6106449e-03 2.7559721e-03 9.6189010e-01
 2.2377348e-05]
96.19 % this is move №  5


In [477]:
predictArr = seq_model.predict(predict_move_6)
print(predictArr[0])

maxPercentage = 0
for i in enumerate(predictArr[0]):
    if(i[1]>maxPercentage):
        maxPercentage=i[1]
        move=i[0]+1     
print(round(maxPercentage*100, 2),"% this is move № ", move)

[2.9434954e-05 5.9605616e-01 4.2752945e-03 1.8771590e-03 1.7667185e-04
 8.4831101e-01]
84.83 % this is move №  6
