In [198]:
import numpy as np
import os
import pandas as pd
import tensorflow as tf
import matplotlib
import keras
from keras import layers

Using TensorFlow backend.


In [199]:
data_path = os.chdir("C:\\Users\\NoMad\\PycharmProjects\\SANEM\\movements")

In [200]:
# другой вариант таблицы, где 25 - число движений, 24 - число пространственных переменных, n - число моментов, потребовавшихся для записи движения
# (25, 24, n)
maxlen = 0
flag = False
for i in range(1,7):
    for j in range(1,10):
        data1 = np.array(pd.read_csv(f"m0{i}_s0{j}_e01_positions.txt", sep=','))
        data1 = np.array([data1[:, 42:].transpose()])
        if(maxlen<data1.shape[2]):
            maxlen = data1.shape[2]

for i in range(1,7):
    for j in range(1,5):
        if(flag==False):
            data1 = np.array(pd.read_csv(f"m0{i}_s0{j}_e01_positions.txt", sep=','))
            data1 = np.array([data1[:, 42:].transpose()])
            x_train = np.zeros((data1.shape[0],data1.shape[1],maxlen))
            x_train[:data1.shape[0],:data1.shape[1],:data1.shape[2]] = data1
            flag=True
            continue
        data1 = np.array(pd.read_csv(f"m0{i}_s0{j}_e01_positions.txt", sep=','))
        data1 = np.array([data1[:, 42:].transpose()])
        if(data1.shape[2]<maxlen):
            newdata = np.zeros((data1.shape[0],data1.shape[1],maxlen))
            newdata[:data1.shape[0],:data1.shape[1],:data1.shape[2]] = data1
            x_train = np.append(x_train, newdata, axis=0)
        elif(data1.shape[2]==maxlen):
            x_train = np.append(x_train, data1, axis=0)

print(x_train.shape)

(24, 24, 159)


In [201]:
x_train = x_train.reshape(x_train.shape[0], 24, x_train.shape[2], 1)
x_train = x_train.astype('float32')
print(x_train.shape)

(24, 24, 159, 1)


In [202]:
# проверочные данные:
predict_move_1 = np.array(pd.read_csv('m01_s01_e05_positions.txt', sep=','))
predict_move_1 = np.array([predict_move_1[:x_train.shape[2], 42:].transpose()])
if(predict_move_1.shape[2]<maxlen):
    newdata = np.zeros((predict_move_1.shape[0],predict_move_1.shape[1],maxlen))
    newdata[:predict_move_1.shape[0],:predict_move_1.shape[1],:predict_move_1.shape[2]] = predict_move_1
    predict_move_1 = newdata
print(predict_move_1.shape)
predict_move_1 = predict_move_1.reshape(predict_move_1.shape[0], 24, predict_move_1.shape[2], 1)
predict_move_1 = predict_move_1.astype('float32')
print("predict_move_1 = ",predict_move_1.shape)

predict_move_2 = np.array(pd.read_csv('m02_s01_e01_positions.txt', sep=','))
predict_move_2 = np.array([predict_move_2[:x_train.shape[2], 42:].transpose()])
if(predict_move_2.shape[2]<maxlen):
    newdata = np.zeros((predict_move_2.shape[0],predict_move_2.shape[1],maxlen))
    newdata[:predict_move_2.shape[0],:predict_move_2.shape[1],:predict_move_2.shape[2]] = predict_move_2
    predict_move_2 = newdata
print(predict_move_2.shape)
predict_move_2 = predict_move_2.reshape(predict_move_2.shape[0], 24, predict_move_2.shape[2], 1)
predict_move_2 = predict_move_2.astype('float32')
print("predict_move_2 = ",predict_move_2.shape)

predict_move_3 = np.array(pd.read_csv('m03_s02_e02_positions.txt', sep=','))
predict_move_3 = np.array([predict_move_3[:x_train.shape[2], 42:].transpose()])
if(predict_move_3.shape[2]<maxlen):
    newdata = np.zeros((predict_move_3.shape[0],predict_move_3.shape[1],maxlen))
    newdata[:predict_move_3.shape[0],:predict_move_3.shape[1],:predict_move_3.shape[2]] = predict_move_3
    predict_move_3 = newdata
print(predict_move_3.shape)
predict_move_3 = predict_move_3.reshape(predict_move_3.shape[0], 24, predict_move_3.shape[2], 1)
predict_move_3 = predict_move_3.astype('float32')
print("predict_move_3 = ",predict_move_3.shape)

predict_move_4 = np.array(pd.read_csv('m04_s01_e01_positions.txt', sep=','))
predict_move_4 = np.array([predict_move_4[:x_train.shape[2], 42:].transpose()])
if(predict_move_4.shape[2]<maxlen):
    newdata = np.zeros((predict_move_4.shape[0],predict_move_4.shape[1],maxlen))
    newdata[:predict_move_4.shape[0],:predict_move_4.shape[1],:predict_move_4.shape[2]] = predict_move_4
    predict_move_4 = newdata
print(predict_move_4.shape)
predict_move_4 = predict_move_4.reshape(predict_move_4.shape[0], 24, predict_move_4.shape[2], 1)
predict_move_4 = predict_move_4.astype('float32')
print("predict_move_4 = ",predict_move_4.shape)

predict_move_5 = np.array(pd.read_csv('m05_s01_e01_positions.txt', sep=','))
predict_move_5 = np.array([predict_move_5[:x_train.shape[2], 42:].transpose()])
if(predict_move_5.shape[2]<maxlen):
    newdata = np.zeros((predict_move_5.shape[0],predict_move_5.shape[1],maxlen))
    newdata[:predict_move_5.shape[0],:predict_move_5.shape[1],:predict_move_5.shape[2]] = predict_move_5
    predict_move_5 = newdata
print(predict_move_5.shape)
predict_move_5 = predict_move_5.reshape(predict_move_5.shape[0], 24, predict_move_5.shape[2], 1)
predict_move_5 = predict_move_5.astype('float32')
print("predict_move_5 = ",predict_move_5.shape)

predict_move_6 = np.array(pd.read_csv('m06_s01_e05_positions.txt', sep=','))
predict_move_6 = np.array([predict_move_6[:x_train.shape[2], 42:].transpose()])
if(predict_move_6.shape[2]<maxlen):
    newdata = np.zeros((predict_move_6.shape[0],predict_move_6.shape[1],maxlen))
    newdata[:predict_move_6.shape[0],:predict_move_6.shape[1],:predict_move_6.shape[2]] = predict_move_6
    predict_move_6 = newdata
print(predict_move_6.shape)
predict_move_6 = predict_move_6.reshape(predict_move_6.shape[0], 24, predict_move_6.shape[2], 1)
predict_move_6 = predict_move_6.astype('float32')
print("predict_move_6 = ",predict_move_6.shape)

(1, 24, 159)
predict_move_1 =  (1, 24, 159, 1)
(1, 24, 159)
predict_move_2 =  (1, 24, 159, 1)
(1, 24, 159)
predict_move_3 =  (1, 24, 159, 1)
(1, 24, 159)
predict_move_4 =  (1, 24, 159, 1)
(1, 24, 159)
predict_move_5 =  (1, 24, 159, 1)
(1, 24, 159)
predict_move_6 =  (1, 24, 159, 1)


In [203]:
# выходной набор данных. Столбец с единицей соответствует номеру соответствующего движения (движений всего 6) 
# y_train = [[1,0,0,0,0,0], [1,0,0,0,0,0], [1,0,0,0,0,0], [1,0,0,0,0,0], [1,0,0,0,0,0],
#            [0,1,0,0,0,0], [0,1,0,0,0,0], [0,1,0,0,0,0], [0,1,0,0,0,0],
#            [0,0,1,0,0,0], [0,0,1,0,0,0], [0,0,1,0,0,0], [0,0,1,0,0,0],
#            [0,0,0,1,0,0], [0,0,0,1,0,0], [0,0,0,1,0,0], [0,0,0,1,0,0],
#            [0,0,0,0,1,0], [0,0,0,0,1,0], [0,0,0,0,1,0], [0,0,0,0,1,0],
#            [0,0,0,0,0,1], [0,0,0,0,0,1], [0,0,0,0,0,1]]

y_train = [0,0,0,0,1,1,1,1,2,2,2,2,3,3,3,3,4,4,4,4,5,5,5,5]
y_train = np.array(y_train, dtype=np.float32)
y_train = keras.utils.to_categorical(y_train)
print(y_train)

[[1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]]


In [204]:
# другой вариант нейросети (сверточная)
input = keras.Input(shape=(24,x_train.shape[2],1))
inputs = layers.Convolution2D(24, input_shape=(24,), kernel_size=(3,1), activation="sigmoid")(input)
hidden1 = layers.Dense(8, activation="softmax")(inputs)
hidden1 = layers.Dropout(0.2)(hidden1)
h1 = layers.Flatten()(hidden1)
outputs = layers.Dense(6, activation="sigmoid")(h1)

seq_model = keras.Model(inputs=input, outputs=outputs, name="sequential_or_what")
seq_model.summary()


Model: "sequential_or_what"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_22 (InputLayer)        (None, 24, 159, 1)        0         
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 22, 159, 24)       96        
_________________________________________________________________
dense_1 (Dense)              (None, 22, 159, 8)        200       
_________________________________________________________________
dropout_1 (Dropout)          (None, 22, 159, 8)        0         
_________________________________________________________________
flatten_1 (Flatten)          (None, 27984)             0         
_________________________________________________________________
dense_2 (Dense)              (None, 6)                 167910    
Total params: 168,206
Trainable params: 168,206
Non-trainable params: 0
__________________________________________

In [205]:
seq_model.compile(
    optimizer=keras.optimizers.Nadam(),
    loss=keras.losses.BinaryCrossentropy(),
    metrics=['accuracy']
)

In [206]:
seq_model.fit(x_train,y_train,epochs=200,batch_size=1)

Epoch 1/200
24/24 [==============================] - 0s 20ms/step - loss: 1.2359 - accuracy: 0.7361
Epoch 2/200
24/24 [==============================] - 0s 7ms/step - loss: 1.0559 - accuracy: 0.7222
Epoch 3/200
24/24 [==============================] - 0s 7ms/step - loss: 1.1487 - accuracy: 0.6667
Epoch 4/200
24/24 [==============================] - 0s 8ms/step - loss: 0.9551 - accuracy: 0.7083
Epoch 5/200
24/24 [==============================] - 0s 7ms/step - loss: 0.9640 - accuracy: 0.7083
Epoch 6/200
24/24 [==============================] - 0s 7ms/step - loss: 0.8402 - accuracy: 0.7431
Epoch 7/200
24/24 [==============================] - 0s 8ms/step - loss: 0.8532 - accuracy: 0.7431
Epoch 8/200
24/24 [==============================] - 0s 7ms/step - loss: 0.8339 - accuracy: 0.7778
Epoch 9/200
24/24 [==============================] - 0s 8ms/step - loss: 0.8656 - accuracy: 0.7361: 0s - loss: 0.9613 - accuracy: 0.
Epoch 10/200
24/24 [==============================] - 0s 7ms/step - loss: 

24/24 [==============================] - 0s 8ms/step - loss: 0.0119 - accuracy: 1.0000
Epoch 82/200
24/24 [==============================] - 0s 8ms/step - loss: 0.0079 - accuracy: 1.0000
Epoch 83/200
24/24 [==============================] - 0s 8ms/step - loss: 0.0112 - accuracy: 1.0000
Epoch 84/200
24/24 [==============================] - 0s 8ms/step - loss: 0.0038 - accuracy: 1.0000
Epoch 85/200
24/24 [==============================] - 0s 8ms/step - loss: 0.0059 - accuracy: 1.0000
Epoch 86/200
24/24 [==============================] - 0s 8ms/step - loss: 0.0071 - accuracy: 1.0000
Epoch 87/200
24/24 [==============================] - 0s 8ms/step - loss: 0.0064 - accuracy: 1.0000
Epoch 88/200
24/24 [==============================] - 0s 8ms/step - loss: 0.0070 - accuracy: 1.0000
Epoch 89/200
24/24 [==============================] - 0s 8ms/step - loss: 0.0073 - accuracy: 1.0000
Epoch 90/200
24/24 [==============================] - 0s 8ms/step - loss: 0.0436 - accuracy: 0.9861
Epoch 91/200


24/24 [==============================] - 0s 8ms/step - loss: 7.0902e-04 - accuracy: 1.0000
Epoch 162/200
24/24 [==============================] - 0s 8ms/step - loss: 6.3799e-04 - accuracy: 1.0000
Epoch 163/200
24/24 [==============================] - 0s 8ms/step - loss: 4.0941e-04 - accuracy: 1.0000
Epoch 164/200
24/24 [==============================] - 0s 8ms/step - loss: 5.6677e-04 - accuracy: 1.0000
Epoch 165/200
24/24 [==============================] - 0s 7ms/step - loss: 8.1294e-04 - accuracy: 1.0000
Epoch 166/200
24/24 [==============================] - 0s 8ms/step - loss: 6.3682e-04 - accuracy: 1.0000
Epoch 167/200
24/24 [==============================] - 0s 8ms/step - loss: 6.4789e-04 - accuracy: 1.0000
Epoch 168/200
24/24 [==============================] - 0s 8ms/step - loss: 5.6087e-04 - accuracy: 1.0000
Epoch 169/200
24/24 [==============================] - 0s 7ms/step - loss: 9.3944e-04 - accuracy: 1.0000
Epoch 170/200
24/24 [==============================] - 0s 8ms/step - 

In [207]:
predictArr = seq_model.predict(predict_move_1)
print(predictArr[0])

maxPercentage = 0
for i in enumerate(predictArr[0]):
    if(i[1]>maxPercentage):
        maxPercentage=i[1]
        move=i[0]+1     
print(round(maxPercentage*100, 2),"% this is move № ", move)

[9.6182770e-01 6.2251279e-06 4.4706944e-01 2.9892047e-04 5.2881088e-11
 2.0557371e-15]
96.18 % this is move №  1


In [208]:
predictArr = seq_model.predict(predict_move_2)
print(predictArr[0])

maxPercentage = 0
for i in enumerate(predictArr[0]):
    if(i[1]>maxPercentage):
        maxPercentage=i[1]
        move=i[0]+1     
print(round(maxPercentage*100, 2),"% this is move № ", move)

[1.8814696e-06 9.9805826e-01 4.1145879e-05 5.1128232e-08 6.3118744e-10
 1.6417458e-07]
99.81 % this is move №  2


In [209]:
predictArr = seq_model.predict(predict_move_3)
print(predictArr[0])

maxPercentage = 0
for i in enumerate(predictArr[0]):
    if(i[1]>maxPercentage):
        maxPercentage=i[1]
        move=i[0]+1     
print(round(maxPercentage*100, 2),"% this is move № ", move)

[5.6370940e-14 1.5894412e-06 4.5105279e-04 7.2422512e-07 9.9999440e-01
 1.8508417e-19]
100.0 % this is move №  5


In [210]:
predictArr = seq_model.predict(predict_move_4)
print(predictArr[0])

maxPercentage = 0
for i in enumerate(predictArr[0]):
    if(i[1]>maxPercentage):
        maxPercentage=i[1]
        move=i[0]+1     
print(round(maxPercentage*100, 2),"% this is move № ", move)

[1.5167090e-04 3.1395169e-09 1.4401225e-03 9.9923217e-01 1.8135266e-05
 3.2402168e-11]
99.92 % this is move №  4


In [211]:
predictArr = seq_model.predict(predict_move_5)
print(predictArr[0])

maxPercentage = 0
for i in enumerate(predictArr[0]):
    if(i[1]>maxPercentage):
        maxPercentage=i[1]
        move=i[0]+1     
print(round(maxPercentage*100, 2),"% this is move № ", move)

[5.9898070e-04 8.4135534e-09 3.9229371e-07 3.0496810e-04 9.9956232e-01
 2.2745204e-16]
99.96 % this is move №  5


In [212]:
predictArr = seq_model.predict(predict_move_6)
print(predictArr[0])

maxPercentage = 0
for i in enumerate(predictArr[0]):
    if(i[1]>maxPercentage):
        maxPercentage=i[1]
        move=i[0]+1     
print(round(maxPercentage*100, 2),"% this is move № ", move)

[1.7600589e-12 6.3872898e-01 6.7289980e-06 2.9334251e-06 2.6670715e-09
 6.9082993e-01]
69.08 % this is move №  6


In [213]:
model_json = seq_model.to_json()
with open("C:\\Users\\NoMad\\PycharmProjects\\SANEM\\model\\1model.json", "w") as json_file:
    json_file.write(model_json)
seq_model.save_weights("C:\\Users\\NoMad\\PycharmProjects\\SANEM\\model\\1weights.h5")