In [84]:
import numpy as np
import os
import pandas as pd
import tensorflow as tf
import matplotlib
from tensorflow import keras
from tensorflow.keras import layers

In [3]:
data_path = os.chdir("C:\\Users\\NoMad\\PycharmProjects\\SANEM\\movements")

In [51]:
# сборка входного набора из 25 таблиц(24 столбца, n строк) с движениями (первые 5 - первое движение, дальнейших движений - по 4), лучше не придумал
# (25, n, 24)
x_train = np.array(pd.read_csv('m01_s01_e01_positions.txt', sep=','))
x_train = np.array([x_train[:, 42:]])
print(x_train.shape)

for i in range(1,7):
    for j in range(2,6):
        data1 = np.array(pd.read_csv(f"m0{i}_s0{j}_e01_positions.txt", sep=','))
        data1 = np.array([data1[:, 42:]])
        if(x_train.shape[1]>data1.shape[1]):
            x_train = x_train[:,:data1.shape[1],:]
            x_train = np.append(x_train, data1, axis=0)
        elif(x_train.shape[1]<data1.shape[1]):
            data1 = data1[:,:x_train.shape[1],:]
            x_train = np.append(x_train, data1, axis=0)

print(x_train.shape)

(1, 72, 24)
(25, 51, 24)


In [4]:
# другой вариант таблицы, где 25 - число движений, 24 - число пространственных переменных, n - число моментов, потребовавшихся для записи движения
# (25, 24, n)
x_train = np.array(pd.read_csv('m01_s01_e01_positions.txt', sep=','))
x_train = np.array([x_train[:, 42:].transpose()])
print(x_train.shape)

for i in range(1,7):
    for j in range(2,6):
        data1 = np.array(pd.read_csv(f"m0{i}_s0{j}_e01_positions.txt", sep=','))
        data1 = np.array([data1[:, 42:].transpose()])

        if(x_train.shape[2]>data1.shape[2]):
            x_train = x_train[:,:,:data1.shape[2]]
            x_train = np.append(x_train, data1, axis=0)
        elif(x_train.shape[2]<data1.shape[2]):
            data1 = data1[:,:,:x_train.shape[2]]
            x_train = np.append(x_train, data1, axis=0)

print(x_train.shape)

(1, 24, 72)
(25, 24, 51)


In [41]:
x_train = x_train.reshape(x_train.shape[0], 24, x_train.shape[2], 1)
x_train = x_train.astype('float32')
print(x_train)

array([[[[ 6.886960e+00],
         [ 6.887050e+00],
         [ 6.904540e+00],
         ...,
         [ 5.988530e+00],
         [ 5.726570e+00],
         [ 5.682970e+00]],

        [[ 4.082000e-02],
         [ 5.412000e-02],
         [ 7.913000e-02],
         ...,
         [ 2.439140e+00],
         [ 2.345520e+00],
         [ 2.139840e+00]],

        [[ 3.570080e+00],
         [ 3.570080e+00],
         [ 3.570080e+00],
         ...,
         [ 2.690270e+00],
         [ 2.809610e+00],
         [ 2.890570e+00]],

        ...,

        [[ 0.000000e+00],
         [ 0.000000e+00],
         [ 0.000000e+00],
         ...,
         [ 0.000000e+00],
         [ 0.000000e+00],
         [ 0.000000e+00]],

        [[ 1.000000e-05],
         [ 1.000000e-05],
         [ 1.000000e-05],
         ...,
         [ 1.000000e-05],
         [ 1.000000e-05],
         [ 1.000000e-05]],

        [[ 1.221943e+01],
         [ 1.203030e+01],
         [ 1.166305e+01],
         ...,
         [ 1.108224e+01],
        

In [161]:
# проверочные данные:
predict_move_2 = np.array(pd.read_csv('m02_s01_e01_positions.txt', sep=','))
predict_move_2 = np.array([predict_move_2[:51, 42:].transpose()])
print(predict_move_2.shape)
predict_move_2 = predict_move_2.reshape(predict_move_2.shape[0], 24, predict_move_2.shape[2], 1)
predict_move_2 = predict_move_2.astype('float32')
print("predict_move_2 = ",predict_move_2.shape)

predict_move_4 = np.array(pd.read_csv('m04_s01_e01_positions.txt', sep=','))
predict_move_4 = np.array([predict_move_4[:51, 42:].transpose()])
print(predict_move_4.shape)
predict_move_4 = predict_move_4.reshape(predict_move_4.shape[0], 24, predict_move_4.shape[2], 1)
predict_move_4 = predict_move_4.astype('float32')
print("predict_move_4 = ",predict_move_4.shape)

predict_move_5 = np.array(pd.read_csv('m05_s01_e01_positions.txt', sep=','))
predict_move_5 = np.array([predict_move_5[:51, 42:].transpose()])
print(predict_move_5.shape)
predict_move_5 = predict_move_5.reshape(predict_move_5.shape[0], 24, predict_move_5.shape[2], 1)
predict_move_5 = predict_move_5.astype('float32')
print("predict_move_5 = ",predict_move_5.shape)

predict_move_6 = np.array(pd.read_csv('m06_s01_e05_positions.txt', sep=','))
predict_move_6 = np.array([predict_move_6[:51, 42:].transpose()])
print(predict_move_6.shape)
predict_move_6 = predict_move_6.reshape(predict_move_6.shape[0], 24, predict_move_6.shape[2], 1)
predict_move_6 = predict_move_6.astype('float32')
print("predict_move_6 = ",predict_move_6.shape)

(1, 24, 51)
predict_move_2 =  (1, 24, 51, 1)
(1, 24, 51)
predict_move_4 =  (1, 24, 51, 1)
(1, 24, 51)
predict_move_5 =  (1, 24, 51, 1)
(1, 24, 51)
predict_move_6 =  (1, 24, 51, 1)


In [42]:
# выходной набор данных. Столбец с единицей соответствует номеру соответствующего движения (движений всего 6) 
# y_train = [[1,0,0,0,0,0], [1,0,0,0,0,0], [1,0,0,0,0,0], [1,0,0,0,0,0], [1,0,0,0,0,0],
#            [0,1,0,0,0,0], [0,1,0,0,0,0], [0,1,0,0,0,0], [0,1,0,0,0,0],
#            [0,0,1,0,0,0], [0,0,1,0,0,0], [0,0,1,0,0,0], [0,0,1,0,0,0],
#            [0,0,0,1,0,0], [0,0,0,1,0,0], [0,0,0,1,0,0], [0,0,0,1,0,0],
#            [0,0,0,0,1,0], [0,0,0,0,1,0], [0,0,0,0,1,0], [0,0,0,0,1,0],
#            [0,0,0,0,0,1], [0,0,0,0,0,1], [0,0,0,0,0,1]]

y_train = [0,0,0,0,0,1,1,1,1,2,2,2,2,3,3,3,3,4,4,4,4,5,5,5,5]
y_train = np.array(y_train, dtype=np.float32)
y_train = keras.utils.to_categorical(y_train)
print(y_train)

[[1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]]


In [137]:
# другой вариант нейросети (сверточная)
input = keras.Input(shape=(24,x_train.shape[2],1))
inputs = layers.Convolution2D(25, input_shape=(24,), kernel_size=(3,1), activation="relu")(input)
hidden1 = layers.Convolution2D(25, kernel_size=(3,1), activation="softmax")(inputs)
h1 = layers.Flatten()(hidden1)
outputs = layers.Dense(6, activation="sigmoid")(h1)

seq_model = keras.Model(inputs=input, outputs=outputs, name="sequential_or_what")
seq_model.summary()

Model: "sequential_or_what"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_23 (InputLayer)        [(None, 24, 51, 1)]       0         
_________________________________________________________________
conv2d_57 (Conv2D)           (None, 22, 51, 25)        100       
_________________________________________________________________
conv2d_58 (Conv2D)           (None, 20, 51, 25)        1900      
_________________________________________________________________
flatten_17 (Flatten)         (None, 25500)             0         
_________________________________________________________________
dense_15 (Dense)             (None, 6)                 153006    
Total params: 155,006
Trainable params: 155,006
Non-trainable params: 0
_________________________________________________________________


In [138]:
keras.utils.plot_model(seq_model, "first_model.png")
keras.utils.plot_model(seq_model, "first_model_with_shape_info.png", show_shapes=True)

Failed to import pydot. You must install pydot and graphviz for `pydotprint` to work.
Failed to import pydot. You must install pydot and graphviz for `pydotprint` to work.


In [139]:
seq_model.compile(
    optimizer=keras.optimizers.Adam(),
    loss=keras.losses.BinaryCrossentropy(),
    metrics=['accuracy']
)

In [140]:
seq_model.fit(x_train,y_train,epochs=100,batch_size=2)

Epoch 1/100
13/13 [==============================] - 0s 11ms/step - loss: 0.6164 - accuracy: 0.0800
Epoch 2/100
13/13 [==============================] - 0s 12ms/step - loss: 0.5640 - accuracy: 0.0400
Epoch 3/100
13/13 [==============================] - ETA: 0s - loss: 0.4675 - accuracy: 0.2778 - 0s 12ms/step - loss: 0.4590 - accuracy: 0.2800
Epoch 4/100
13/13 [==============================] - 0s 12ms/step - loss: 0.4456 - accuracy: 0.2000
Epoch 5/100
13/13 [==============================] - 0s 11ms/step - loss: 0.4659 - accuracy: 0.2800
Epoch 6/100
13/13 [==============================] - 0s 11ms/step - loss: 0.4769 - accuracy: 0.4000
Epoch 7/100
13/13 [==============================] - 0s 11ms/step - loss: 0.4552 - accuracy: 0.2800
Epoch 8/100
13/13 [==============================] - 0s 11ms/step - loss: 0.4313 - accuracy: 0.4400
Epoch 9/100
13/13 [==============================] - 0s 12ms/step - loss: 0.3909 - accuracy: 0.3200
Epoch 10/100
13/13 [==============================] - 0s

13/13 [==============================] - 0s 11ms/step - loss: 0.0106 - accuracy: 1.0000
Epoch 82/100
13/13 [==============================] - 0s 12ms/step - loss: 0.0104 - accuracy: 1.0000
Epoch 83/100
13/13 [==============================] - 0s 11ms/step - loss: 0.0097 - accuracy: 1.0000
Epoch 84/100
13/13 [==============================] - 0s 11ms/step - loss: 0.0090 - accuracy: 1.0000
Epoch 85/100
13/13 [==============================] - 0s 11ms/step - loss: 0.0090 - accuracy: 1.0000
Epoch 86/100
13/13 [==============================] - 0s 11ms/step - loss: 0.0088 - accuracy: 1.0000
Epoch 87/100
13/13 [==============================] - 0s 11ms/step - loss: 0.0091 - accuracy: 1.0000
Epoch 88/100
13/13 [==============================] - 0s 11ms/step - loss: 0.0082 - accuracy: 1.0000
Epoch 89/100
13/13 [==============================] - 0s 11ms/step - loss: 0.0078 - accuracy: 1.0000
Epoch 90/100
13/13 [==============================] - 0s 11ms/step - loss: 0.0078 - accuracy: 1.0000
Epo

In [141]:
seq_model.evaluate(predict_move_5, np.array([[0, 0, 0, 0, 1, 0,]]))

1/1 [==============================] - 0s 3ms/step - loss: 0.0386 - accuracy: 1.0000


[0.0385507307946682, 1.0]

In [142]:
seq_model.predict(predict_move_2)

array([[3.5170973e-03, 8.4658480e-01, 2.0497590e-03, 4.8805356e-05,
        4.9884629e-04, 5.1110322e-03]], dtype=float32)

In [162]:
seq_model.predict(predict_move_4)

array([[3.3284089e-04, 1.6902557e-05, 1.9586615e-02, 9.3507916e-01,
        2.9926017e-02, 1.7981991e-04]], dtype=float32)

In [160]:
seq_model.predict(predict_move_5)

array([[3.5221018e-02, 7.7020028e-05, 2.2192088e-04, 2.3544098e-03,
        9.7347653e-01, 1.1705681e-05]], dtype=float32)

In [158]:
seq_model.predict(predict_move_6)

array([[7.5886055e-05, 9.8111731e-01, 1.0178864e-03, 5.5967092e-05,
        3.2005925e-04, 4.4385005e-02]], dtype=float32)